//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_P_Message
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public string Message { get; set; }
        public string Reason { get; set; }
        public System.DateTime SendTime { get; set; }
        public int State { get; set; }
        public string ReplyMessage { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public string ReplyAdmin { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
