//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public int ID { get; set; }
        public int AdminID { get; set; }
        public System.DateTime PublishTime { get; set; }
        public string Topic { get; set; }
        public string Content { get; set; }
    
        public virtual AdminT AdminT { get; set; }
    }
}
