//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public string IDCard { get; set; }
        public string Address { get; set; }
        public string Native_place { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int DptID { get; set; }
        public string Diploma { get; set; }
        public string Major { get; set; }
        public string Remark { get; set; }
        public string WorkExper { get; set; }
        public int State { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
