//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PersonManagementEntities : DbContext
    {
        public PersonManagementEntities()
            : base("name=PersonManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminT> AdminT { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employment> Employment { get; set; }
        public virtual DbSet<Pay> Pay { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Reward> Reward { get; set; }
        public virtual DbSet<Train> Train { get; set; }
        public virtual DbSet<A_P_Message> A_P_Message { get; set; }
        public virtual DbSet<A_U_Message> A_U_Message { get; set; }
        public virtual DbSet<UserT> UserT { get; set; }
    
        public virtual ObjectResult<proc_pay_Result> proc_pay(Nullable<System.DateTime> findDate)
        {
            var findDateParameter = findDate.HasValue ?
                new ObjectParameter("FindDate", findDate) :
                new ObjectParameter("FindDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_pay_Result>("proc_pay", findDateParameter);
        }
    }
}
