//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonManagementEntities : DbContext
    {
        public PersonManagementEntities()
            : base("name=PersonManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminT> AdminT { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employment> Employment { get; set; }
        public virtual DbSet<Pay> Pay { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Reward> Reward { get; set; }
        public virtual DbSet<Train> Train { get; set; }
    }
}
