//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserT()
        {
            this.A_U_Message = new HashSet<A_U_Message>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_U_Message> A_U_Message { get; set; }
    }
}
